config/routes.rb
Resistance::Application.routes.draw do
  resources :users
  
  resources :sessions, only: [:new, :create, :destroy]
  resources :games,    only: [:show, :create, :destroy]
  resources :players,  only: [:create, :destroy]
  
  root 'static_pages#home'

  match '/signup',  to: 'users#new',             via: 'get'
  match '/signin',  to: 'sessions#new',          via: 'get'
  match '/signout', to: 'sessions#destroy',      via: 'delete'
  match '/help',    to: 'static_pages#help',     via: 'get'
  match '/about',   to: 'static_pages#about',    via: 'get'
  match '/contact', to: 'static_pages#contact',  via: 'get'
  

end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <dev class="alert alert-error">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </dev>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>
      

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <p><%= "#{@feed_items.count} games"%></p>
  <ol class="games">
    <%= render partial: 'shared/feed_item', collection: @feed_items %>
  </ol>
  <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_feed_item.html.erb
<li id="<%= feed_item.id %>">
  <%= link_to gravatar_for(feed_item.owner, size: 30), feed_item.owner %>

  <span class="game"><%= link_to feed_item.summary, feed_item%></span>

  <span class="timestamp">
    Started <%= time_ago_in_words(feed_item.created_at) %> ago.  By 
  </span>

  <span class="user">
    <%= link_to feed_item.owner.name, feed_item.owner %>
  </span>

  <% if current_user?(feed_item.owner) %>
    <%= link_to "delete", feed_item, method: :delete,
        data: { confirm: "Sure?" },
        title: feed_item.summary %>
  <% end %>

</li>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= game_user_path(@user) %>">
    <strong id="games" class="stat">
      <%= @user.games.count %>
    </strong>
    games
  </a>
</div>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user, size: 52), current_user %>
<h1><%= current_user.name %></h1>
<span><%= link_to "view my profile", current_user %></span>
<span><%= pluralize(current_user.games.count, "games") %></span>